# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Gazetteer-HeavensAbove
version:      0.15
version_from: HeavensAbove.pm
installdirs:  site
requires:
    HTML::Form:                    0
    HTML::TreeBuilder:             3.13
    LWP::UserAgent:                2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
