---
name: WWW-Gazetteer-HeavensAbove
version: 0.18
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
abstract: Find location of world towns and cities
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Form: 0
  HTML::TreeBuilder: 3.13
  LWP::UserAgent: 2
  Test::More: 0
provides:
  WWW::Gazetteer::HeavensAbove:
    file: lib/WWW/Gazetteer/HeavensAbove.pm
    version: 0.18
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
